apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-3m2nmz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3m2nmz
  namespace: my-nginx-3m2nmz
  labels:
    name: nginx-3m2nmz
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-3m2nmz
  template:
    metadata:
      namespace: my-nginx-3m2nmz
      labels:
        name: nginx-3m2nmz
    spec:
      containers:
      - name: nginx-3m2nmz
        image: nginx
        ports:
        - containerPort: 80

